Update p3 d types with reflector depth
globallightingdata/website pull request #90
Opened 2024-11-05 16:41 UTC by alexrelux

Update p3 d types with reflector depth

2024-11-08 07:56 UTC, Kurpanik commented
Die Überarbeitung weicht vom Stil der Seite ab. Alle Wörter, die Elementen in XML entsprechen, sind in der Doku besonders hervorgehoben. Wir sollten weiterhin einen einheitlichen Stil pflegen:

Bisher, richtig:
![grafik](https://github.com/user-attachments/assets/d8f0d337-016c-4589-b9b4-3ae8122c02db)

Jetzt
![grafik](https://github.com/user-attachments/assets/2f07af52-7ad3-4806-b5fb-40fdb0de9f27)

2024-11-08 07:56 UTC, Kurpanik commented
Das Bild passt nicht mehr zu den Parametern

2024-11-08 07:56 UTC, Kurpanik requested changes
Siehe Kommentare

2024-11-22 10:14 UTC, alexrelux commented
Ja, das Team muss noch Änderungen umsetzen. Solange sich das verzögert, sollten wir die Veröffentlichung zurückhalten.

2024-11-22 10:25 UTC, Kurpanik commented
Alles klar

2025-02-05 16:43 UTC, alexrelux commented
@Kurpanik Hi Alex, so wurde das jetzt implementiert. Gruss Alex

2025-02-06 14:27 UTC, Kurpanik commented
@alexrelux Der PR ist noch im Draft. Sprich die Doku ist jetzt aber noch nicht fertig?

2025-02-06 15:08 UTC, alexrelux commented
ist fertig

2025-02-10 07:21 UTC, merged